version: '3.7'
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - data_volume:/data/db
    ports:
      - "27017:27017"

  java_backend:
    build:
      context: /home/daniel/myApp/javaBackend
      dockerfile: /home/daniel/myApp/javaBackend/Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"
    depends_on:
      - mongodb

volumes:
  data_volume:
